# Generated by Django 4.0.4 on 2022-06-01 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('idSexo', models.AutoField(primary_key=True, serialize=False)),
                ('descSexo', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMascota',
            fields=[
                ('idTipoMascota', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de Mascota')),
                ('descTipoMascota', models.CharField(max_length=15, verbose_name='Descripción de Mascota')),
            ],
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('idRaza', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de Raza')),
                ('descRaza', models.CharField(max_length=40, verbose_name='Descripción Raza')),
                ('tipoMascota', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.tipomascota')),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('idMascota', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de Mascota')),
                ('nombreMascota', models.CharField(max_length=40, verbose_name='Nombre de Mascota')),
                ('edadAnioMascota', models.IntegerField(verbose_name='Edad en Años de Mascota')),
                ('edadMesesMascota', models.IntegerField(verbose_name='Edad en Meses de Mascota')),
                ('estEstirizadoMascota', models.BooleanField(verbose_name='Estado Estirilización de Mascota')),
                ('fotoMascota', models.ImageField(upload_to='static/img/')),
                ('razaMascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.raza')),
                ('sexoMascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sexo')),
            ],
        ),
    ]
