# Generated by Django 4.0.2 on 2022-06-10 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_fundacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundacion',
            name='fotoFundacion',
            field=models.ImageField(default='static/images/fundaciones/5.png', upload_to='static/images/upload/'),
        ),
    ]
