# Generated by Django 4.0.5 on 2022-06-13 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_fundacion_fotofundacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('idPersona', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Persona')),
                ('nombres', models.CharField(max_length=150, verbose_name='Nombres de la persona')),
                ('apellidos', models.CharField(max_length=150, verbose_name='Apellidos de la persona')),
                ('telefono', models.CharField(max_length=12, verbose_name='Teléfono de contacto')),
                ('email', models.CharField(max_length=30, verbose_name='Correo de contacto')),
                ('direccion', models.CharField(max_length=50, verbose_name='Dirección de la persona')),
            ],
        ),
        migrations.AlterField(
            model_name='categoria',
            name='idCategoria',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID de Categoria'),
        ),
        migrations.AlterField(
            model_name='fundacion',
            name='idFundacion',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID de Fundación'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='idMascota',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID de Mascota'),
        ),
        migrations.AlterField(
            model_name='raza',
            name='idRaza',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID de Raza'),
        ),
        migrations.AlterField(
            model_name='tipomascota',
            name='idTipoMascota',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID de Mascota'),
        ),
    ]
