# Generated by Django 4.0.5 on 2022-06-13 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_producto_descripcion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
