# Generated by Django 4.0.5 on 2022-06-14 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID Producto'),
        ),
    ]
