# Generated by Django 4.0.5 on 2022-06-14 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_producto_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='static/images/Bandanas.jpg', upload_to='static/images/upload/'),
        ),
    ]
