# Generated by Django 4.0.5 on 2022-06-14 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(max_length=500, verbose_name='Descripcion Producto'),
        ),
    ]
