# Generated by Django 4.0.5 on 2022-06-14 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_producto_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='static/images/bolsarecoge.jpg', upload_to='static/images/upload'),
        ),
    ]
