# Generated by Django 4.0.5 on 2022-06-14 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_producto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de Cliente')),
                ('nombreCliente', models.CharField(max_length=40, verbose_name='Nombre de Cliente')),
                ('ApellidoCliente', models.CharField(max_length=40, verbose_name='Apellidos de Cliente')),
                ('telefonoCliente', models.CharField(max_length=40, verbose_name='Telefono de Cliente')),
                ('emailCliente', models.CharField(max_length=100, verbose_name='Email de Cliente')),
                ('direccionCliente', models.CharField(max_length=250, verbose_name='Direccion de Cliente')),
                ('RegionCliente', models.CharField(max_length=250, verbose_name='Region de Cliente')),
                ('ComunaCliente', models.CharField(max_length=250, verbose_name='Comuna de Cliente')),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='static/images/bolsarecoge.jpg', upload_to='static/images/upload/'),
        ),
    ]
