# Generated by Django 4.0.5 on 2022-07-04 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundacion',
            name='website',
            field=models.URLField(default='https://todosdecidimos.org/animales/', max_length=150, verbose_name='Pagina Web'),
        ),
        migrations.AlterField(
            model_name='fundacion',
            name='descFundacion',
            field=models.CharField(max_length=500, verbose_name='Descripción de la Fundación'),
        ),
        migrations.AlterField(
            model_name='fundacion',
            name='nombreFundacion',
            field=models.CharField(max_length=150, verbose_name='Fundación'),
        ),
    ]
