# Generated by Django 4.0.5 on 2022-07-13 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0025_producto_nombre_producto_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descuentos',
            fields=[
                ('idDescuento', models.AutoField(primary_key=True, serialize=False, verbose_name='ID del descuento')),
                ('nom_desc', models.CharField(max_length=200, verbose_name='Nombre del descuento')),
                ('porc_desc', models.FloatField(verbose_name='Monto de descuento expresado como flotante')),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('idVenta', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de la venta')),
                ('iddescuento', models.BooleanField(default=False)),
                ('fecha_compra', models.DateTimeField(verbose_name='Datetime de la venta')),
                ('idcategoria_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria', verbose_name='FK de la categoría del producto')),
                ('idproducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto', verbose_name='FK del producto')),
                ('iduser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='FK del usuario')),
            ],
        ),
    ]
